// Speaker notes per slide (0-indexed to match reveal slide order).
window.BZ_NOTES = {
  0: ["Open warm — thank Table Mountain and the summit. This is the practical stuff: free, no jargon, start this week.",
      "Frame the talk: in 2026 your next customer asks Google or AI before they ever call. Let's make sure you get named."],
  1: ["The promise: no jargon, no homework. Four things, all free, all start-this-week.",
      "Tell them you'll repeat a 'Do Monday' action on every slide, so they leave with a checklist."],
  2: ["Gut-punch: before they call — before an agency picks a contractor — they look you up. What they find decides if you get the call.",
      "72% use Google to find local info. The card on screen is a strong profile: photos, reviews, one tap to call.",
      "Local color if it lands: Fresno County, #1 ag county in the nation — let's get found like it."],
  3: ["Into Part 1. You don't need to go viral. You need to show up and show your work."],
  4: ["Rule one: show up. Buffer studied 4.8M posts — skip a week and you fall behind your own growth. Consistency beats the 'magic hour.'",
      "Point at the calendar: it doesn't matter WHICH days, only that you keep them. Three a week is plenty.",
      "Do Monday: pick your days, batch three posts in one sitting."],
  5: ["Your work IS the content — before/after, the crew, a finished job, a happy customer. The phone in your pocket shoots all of it.",
      "Real beats polished. The feed on screen is real photos — that's the bar.",
      "Do Monday: next job, photos at the start, the middle, and the finish."],
  6: ["One job = a week of posts. Walk the sweep: the before + plan, crew on site, the finished after, a 15-sec video, the 5-star review, one quick tip.",
      "This kills 'I have nothing to post.' Do Monday: photograph your next job arrival to handshake — six posts, already done."],
  7: ["Don't be everywhere. Google Business Profile first — it feeds the map and the AI. Then pick ONE more you'll actually keep up.",
      "Consistent on two beats sloppy on five."],
  8: ["Into Part 2. Reviews get you looked up; your website is where they decide — and increasingly where you win contracts."],
  9: ["Reviews are the new word of mouth — for humans AND for the AI that recommends you. 66% research more after a good review; 24% then check your social.",
      "Fresh, steady reviews beat one old batch — the feed on screen shows them coming in.",
      "Do Monday: ask your last three happy customers for a Google review — text them the link."],
  10: ["After they trust you, your site has to deliver in 3 seconds: load fast, look real, show your work, make contact easy.",
       "Slow = gone — mobile bounce climbs as the seconds tick. Do Monday: search your own business on your phone and time it."],
  11: ["You don't have to code. Webflow, Framer, WordPress + Elementor, Squarespace, Wix, Shopify, GoDaddy — each fits a different goal.",
       "Pick the right one, not the loudest ad. A finished site beats a perfect one that never ships. (We help you pick, then build it.)"],
  12: ["62% avoid a business over wrong info online. A dead link or old phone number quietly costs you the job.",
       "Keep it current: same name/address/phone everywhere, working links, the padlock (SSL), backups, recent photos.",
       "And who keeps it alive? 11,334 new WordPress vulnerabilities in 2025, 91% from plugins. If it went down tonight, who fixes it? Do Monday: Google your own business, fix anything wrong."],
  13: ["Your Google Business Profile is your front door — and a top input for whether AI names you. 72% use Google for local info.",
       "Claim it, complete every field, add photos, keep hours right, gather reviews. Highest-leverage free hour you'll spend."],
  14: ["For contractors: the officer Googles you too. Put your SB/DVBE certs, past projects, and a one-page capability statement on your site.",
       "California certifies through OSDS — the door to state contracts. Your site is where they confirm you're real and ready."],
  15: ["Into Part 3. The same tools that grow your business get targeted. A few free habits protect you."],
  16: ["Imposter scams were the #1 reported fraud in 2025: $3.5B. Fake-invoice / 'vendor' emails (business email compromise) cost $3.05B.",
       "AI cuts both ways — cloned voices, convincing emails; $893M to AI-enabled fraud. Walk the red flags: wrong domain, urgency, a new payment account.",
       "Treat any urgent payment request as suspicious."],
  17: ["Five free habits: verify before you pay (call a known number), decide who can approve payments and write it down, turn on two-factor, use a password manager, lock down your site (SSL + backups).",
       "Two-factor is the single biggest lock — and all of these are free."],
  18: ["AI is the marketing department you never had. 58% of small businesses already use it, mostly for marketing and content.",
       "Show it draft a week of captions in seconds — then say it: this is the 80%. Posted raw, you look like everyone.",
       "Three rules: check it (it can be confidently wrong), keep your voice, never paste private or customer data."],
  19: ["The employee that never sleeps. Most inquiries land after hours and the first to reply wins. An AI agent can answer, qualify, and book.",
       "Walk the chat: customer asks, AI offers times, books it. For a roofer on a ladder or a cleaner mid-job, this solves the missed-call problem. You confirm in the morning."],
  20: ["The honest truth — and the whole pitch. AI gets you ~80%: it makes anything look polished in seconds, and identical to everyone else.",
       "Point at the grid — same gradient, same emojis, same everyone. Customers are starting to skip businesses that feel AI-made.",
       "The 20% — your real photos, your voice, your town, keeping it alive — is the difference. Slop is the absence of a decision. Don't avoid AI; aim it."],
  21: ["Recap — the whole talk on one card. Schedule three posts. Photograph your next job. Ask three customers for a review. Google yourself and fix it. Turn on two-factor + a 'verify before you pay' rule.",
       "Tell them to take a photo of this slide."],
  22: ["The offer: a free Online-Presence Check. Four things — does AI name you, is your Google profile complete, does your site load fast and build trust, are your reviews working.",
       "Big QR. 'First 25 from tonight are free.' Contractors: we'll review your capability statement and certs too."],
  23: ["Close on the bridge line: AI does 80%, we do the 20% that makes it yours — and we keep it alive.",
       "Proof: 5.0 on Google, +30% average lift in leads, Fresno, family-operated since 2014, trusted by the SBA, Fresno State, the SBDC. Book a free call. Powering tomorrow, today."],
  24: ["INTERNAL — your run-of-show. Open ~5, social ~17, website ~18, stay-safe ~10, AI + checklist ~5, ask + Q&A ~5. Don't put this on the screen."],
  25: ["INTERNAL — sources and the keep-off list. Don't say the refuted stats. Confirm before stage: the live 'does AI name you' demo for your trade, current tool names/pricing, TikTok status."]
};
